# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'GTThriftShop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Firebase'
  	pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Messaging'
    pod 'Alamofire', '~> 4.4'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'JSQMessagesViewController'
    pod 'SwiftGifOrigin'
end
